// const ErrorIsCheckBiometricAndroid = {
//   NO_HARDWARE: 'BIOMETRIC_ERROR_NO_HARDWARE',
//   HW_UNAVAILABLE: 'BIOMETRIC_ERROR_HW_UNAVAILABLE',
//   NONE_ENROLLED: 'BIOMETRIC_ERROR_NONE_ENROLLED',
// };
