export const ErrorIsCheckBiometricAndroid = {
  NO_HARDWARE: 'BIOMETRIC_ERROR_NO_HARDWARE',
  HW_UNAVAILABLE: 'BIOMETRIC_ERROR_HW_UNAVAILABLE',
  NONE_ENROLLED: 'BIOMETRIC_ERROR_NONE_ENROLLED',
  CREATE_KEY_FAILED: 'CREATE_PUBLIC_PRIVATE_FAILED',
  BIOMETRIC_LOGIN_FAILED: 'LOGIN_FAILED',
};
