export const MY_BIOMETRIC = 'MyBiometrics';

export const ASYNC_STORAGE = {
  API_URL: 'API_URL',
  STATUS_LOGIN: 'STATUS_LOGIN',
  URL_API: 'URL_API',
};

export const BIOMETRIC_SIGNATURE_FAILED = {
  CREATE_KEY_ERROR: MY_BIOMETRIC + 'CreatePrivatePublicError',
  EXIST_KEY_ERROR: MY_BIOMETRIC + 'ExistKeyError',
  DISPLAYING_ERROR: MY_BIOMETRIC + 'DisplayingBiometricsError',
};

export const ERROR_KEY = {
  FAILED_KEY: 'CREATE_KEY_FAILED',
  SIGNATURE_FAILED: 'SIGNATURE_KEY_FAILED',
  BIOMETRICS_FAILED: 'BIOMETRICS_FAILED',
  KEY_ERROR: 'KeyError',
  DEVICED_VERSION_ERRORE: MY_BIOMETRIC + 'VersionDevicedNotSupport',
};
